[project]
name = "devdevbot"
version = "0.1.0"
description = "DevDocBot AI Agent .001 built in lovely python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]
